### ISSUE TITLE
Get the firmware inventory report for a vCenter cluster from OMEVVP

### ISSUE THREAD

**Issue by prasadrao-dell** [dell/omivv#10]
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Requirement Breakdown | Details
-- | --
Objective |  Get the firmware inventory report for a vCenter cluster (particularly, a group) from OMEVVP
Authentication/Authorization |  Authenticate using vCenter credentials (Basic Authorization) and "x_omivv-api-vcenter-identifier" (UUID of the vCenter) as a mandatory header.
List of the tasks in the workflow (in   order) |  <ul><li>Ensure that the vCenter user credentials and the corresponding vCenter UUID are accepted.</li><li>Comply with any input validation (see below)</li><li>Invoke request to retrieve firmware inventory report for a vCenter cluster from OMEVVP</li></li><li>Return the corresponding object</li></ul>
Module type: Library and/or executable |  Both
Input and format |  <ul><li>Accept the following parameters:<ul><li>vCenter uuid (also known as console uuid)</li><li>omevv_group_id</li><li>skip</li><li>top</li></ul></li><li>Mandatory parameters : vCenter uuid, omevv_group_id</li></ul>
Expected output and format   Export required | <ul><li>Following is the expected output of firmware inventory report of a cluster with the given properties:<ul><li>pagingInfo</li><ul><li>totalInstances</li><li>first</li><li>last</li><li>next</li><li>prev</li></ul><li>GroupDeviceFirmwareDetails</li><ul><li>host</li><li>serviceTag</li><li>version</li><li>installationDate</li><li>status</li><li>softwareType</li><li>componentType</li><ul><li>id</li><li>name</li><li>description</li></ul><li>componentId</li><li>vendorId</li><li>subDeviceId</li><li>subVendorId</li><li>pciDeviceId</li><li>deviceDescription</li><li>instanceId</li></ul></ul><li>Export the output with the headers mentioned above.</li></ul>
Concurrency requirement. |  None
Execution model: synchronous or   asynchronous |  Synchronous
Applicable timeouts and retries | Attempt retrieving firmware inventory report for a vCenter cluster managed through OMEVVP upto 3 times only when the failure is on account of a network timeout. On any other types of error for instance, providing invalid input parameters, no retry should be attempted.
Expected error handing |  Handle all the network and non network related errors and log them in a user friendly way.
Expected domain specific validation |  As specified above

</body>

**Comment by pavithra-mahadev** [comment]
https://github.com/dell/omivv/pull/31
