### ISSUE TITLE
Update firmware to a single server in a vSphere cluster using OMEVVP APIs

### ISSUE THREAD

**Issue by prasadrao-dell** [dell/omivv#12]
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Requirement Breakdown | Details
-- | --
Objective |  
Authentication/Authorization |  
List of the tasks in the workflow (in   order) |  
Module type: Library and/or executable |  
Input and format |  
Expected output and format   Export required |  
Concurrency requirement. |  
Execution model: synchronous or   asynchronous |  
Applicable timeouts and retries |  
Expected error handing |  
Expected domain specific validation |  

</body>

**Comment by pavithra-mahadev** [comment]
https://github.com/dell/omivv/pull/47
