### ISSUE TITLE
Register vCenter using OMEVV

### ISSUE THREAD

**Issue by prasadrao-dell** [dell/omivv#18]
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Requirement Breakdown | Details
-- | --
Objective |  Register vCenter using OMEVV. WebClient/PHA extension will be registered. VLCM extension can be optionally registered. Alternatively, VLCM registration can be performed on a vCenter that is already registered for WebClient/PHA.
Authentication/Authorization |  Authenticate using OME credentials (Basic Authorization).
List of the tasks in the workflow (in   order) |  <ul><li>Ensure that the vCenter hostname/ip and user credentials are accepted.</li><li>Invoke request to register</li></li><li>Return registration status and applicable errors if any</li></ul>
Module type: Library and/or executable |  Both
Input and format |  <ul><li>Accept the following parameters:<ul><li>vCenter hostname/IP (mandatory)</li><li>vCenter username/password (mandatory)</li><li>parameter to identify VLCM registration(optional. False if not specified)</li><li>OME username/credential (mandatory)</li></ul></li></ul>
Expected output and format   Export required | <ul><li>Status of the operation and relevant error message if any</li></ul>
Concurrency requirement. |  None
Execution model: synchronous or   asynchronous |  Synchronous
Applicable timeouts and retries | No retry needs to be attempted currently.
Expected error handing |  Handle all the network and non network related errors and log them in a user friendly way.
Expected domain specific validation |  As specified above

</body>

**Comment by pavithra-mahadev** [comment]
https://github.com/dell/omivv/pull/46
