### ISSUE TITLE
Listing host management compliance

### ISSUE THREAD

**Issue by prasadrao-dell** [dell/omivv#20]
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Requirement Breakdown | Details
-- | --
Objective |  Allow identification of the management compliance status of server devices (Undiscovered / Compliant / Non-Compliant / Unsupported).
Authentication/Authorization |  Authenticate using vCenter credentials (Basic Authorization) and "x_omivv-api-vcenter-identifier" (UUID of the vCenter) as a mandatory header.
List of the tasks in the workflow (in   order) |  <ul><li>Ensure that the vCenter user credentials and the corresponding vCenter UUID are accepted.</li><li>Comply with any input validation (see below)</li><li>Invoke request to retrieve compliance info of servers.</li></li><li>Filter based on applicable inputs (complianceFilter)</li><li>Return the corresponding object and export to specified csv file</li></ul>
Module type: Library and/or executable |  Both
Input and format |  <ul><li>Accept the following parameters:<ul><li>vCenter uuid (also known as console uuid)</li><li>VC username/credentials</li><li>Compliance filter(Undiscovered / Compliant / Non-Compliant / Unsupported / All)</li></ul></li></ul>
Expected output and format   Export required | <ul><li>Status of the operation and relevant error message if any</li><li>Export API output object to data file if specified</li></ul>
Concurrency requirement. |  None
Execution model: synchronous or   asynchronous |  Synchronous
Applicable timeouts and retries | No retry needs to be attempted currently.
Expected error handing |  Handle all the network and non network related errors and log them in a user friendly way.
Expected domain specific validation |  As specified above

</body>

**Comment by pavithra-mahadev** [comment]
https://github.com/dell/omivv/pull/26
