### ISSUE TITLE
Auto manage all compliant servers. Should leverage https://github.com/dell/omivv/issues/22

### ISSUE THREAD

**Issue by prasadrao-dell** [dell/omivv#32]
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Requirement Breakdown | Details
-- | --
Objective |  The script should be able to get the required details of hosts to be managed based on Compliance state of the servers and manage them for further monitoring.
Authentication/Authorization |  Authenticate using vCenter credentials (Basic Authorization) and "x_omivv-api-vcenter-identifier" (UUID of the vCenter) as a mandatory header.
List of the tasks in the workflow (in   order) |  <ul><li>Get the servers list using /Consoles/{uuid}/Compliance URI</li><li>Check for servers with compliant and non-compliant state</li><li>Get the host ids of the server which are compliant  and non-compliant(only for Fix compliance reason) and pass as the input for omevvServerManagement.py/createpayload</li></ul>
Module type: Library and/or executable |  Executable
Input and format |  OME IP/Name and creds, VC IP/Name and credentials
Expected output and format   Export required |  Manage Job Id, Export not required
Concurrency requirement. |  None
Execution model: synchronous or   asynchronous |  synchronous
Applicable timeouts and retries |  Attempt reaching the OME/VC upto 3 times only when the failure is on account of a network timeout. On any other types of error for instance, providing invalid input parameters, no retry should be attempted.
Expected error handing |  Handle all the network and non network related errors and log them in a user friendly way.
Expected domain specific validation |  As specified above

</body>

**Comment by pavithra-mahadev** [comment]
Refer PR for more details to call the function - https://github.com/dell/omivv/pull/28/files

**Comment by KristianLamb** [comment]
Complete. Needs changes from branch /usr/abhishek14-Dell/omevvservermanagement before PR to master
