### ISSUE TITLE
Auto upgrade OME adv+ license to servers marked as unsupported in OMEVVP

### ISSUE THREAD

**Issue by prasadrao-dell** [dell/omivv#4]
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Requirement Breakdown | Details
-- | --
Objective |  Upgrading to advanced+ license on non-compliant servers due to unsupported iDRAC license. The license details  are displayed on Management Compliance page in vCenter.
Authentication/Authorization |  Authenticate using vCenter credentials (Basic Authorization) and "x_omivv-api-vcenter-identifier" (UUID of the vCenter) as a mandatory header.
List of the tasks in the workflow (in   order) |  <ul><li>Ensure that the vCenter user credentials and the corresponding vCenter UUID are accepted.</li><li>Comply with any input validation (see below)</li><li>Invoke request to get the compliance details from the provided OME and VC credentials</li><li>Get the list of unsupported iDRAC license status</li><li>Upgrade the iDRAC license to advanced+ license based on the details provided in the csv file</li></ul>
Module type: Library and/or executable |  Executable
Input and format |  <ul><li>Accept the following parameters<ul><li>OME IP with credential details</li><li>VC IP/name with credential details</li><li>csv file location</li></ul>
Expected output and format   Export required |  No. of successful licenses upgraded/failed. No Export required.
Concurrency requirement. |  None
Execution model: synchronous or   asynchronous |  Synchronous
Applicable timeouts and retries |  Attempt to upload the license 3 times, if the server is accessible.
Expected error handing |  Handle all the network and non network related errors and log them in a user friendly way.
Expected domain specific validation |  <ul><li>csv file format to be specified in help option. </li><li>If no credentials are mentioned in the csv file, default credentials(root/calvin) to be used.</li></ul>

</body>

**Comment by pavithra-mahadev** [comment]
https://github.com/dell/omivv/pull/57

**Comment by pavithra-mahadev** [comment]
https://github.com/dell/omivv/pull/57
