### ISSUE TITLE
Creating a repository profile in OMEVVP

### ISSUE THREAD

**Issue by prasadrao-dell** [dell/omivv#5]
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Requirement Breakdown | Details
-- | --
Objective | A repository profile is an OMEVV wrapper to the dell firmware/solution catalogs. Creating a repository profile is a required pre-requisite to begin able to update firmware to server devices using OMEVVP.
Authentication/Authorization | Authenticate using vCenter credentials (Basic Authorization) and "x_omivv-api-vcenter-identifier" (UUID of the vCenter) as a mandatory header.
List of the tasks in the workflow (in   order) |  <ul><li>Ensure that the vCenter user credentials and the corresponding vCenter UUID are accepted.</li><li>Comply with any input validation (see below)</li><li>Invoke request to create a repository profile</li></li><li>Poll until the repository profile is created</li><li>Return repository profile object</li></ul>
Module type: Library and/or executable |  Both
Input and format |  <ul><li>Accept the following parameters<ul><li>profileName</li><li>description</li><li>profileType</li><li>sharePath(Allow CIFS/NFS/HTTP/HTTPs)</li><li>shareCredential</li></li><li>protocolType(CIFS/NFS/HTTP/HTTPS/UNAVAILABLE)</li><li>checkCertificate(true/false)</li><li>createdBy</li></ul></li><li>Following are the mandatory parameters : profileName, profileType, protocolType, sharePath</li></ul>
Expected output and format   Export required | Add log message at various execution steps if provided else output to console. Export is not required.
Concurrency requirement. | None
Execution model: synchronous or   asynchronous | Synchronous
Applicable timeouts and retries | Attempt creating the repository profile upto 3 times only when the failure is on account of a network timeout. On any other types of error for instance, providing invalid share path, no retry should be attempted.
Expected error handing | Handle all the network and non network related errors and log them in a user friendly way.
Expected domain specific validation | As specified above

</body>

**Comment by pavithra-mahadev** [comment]
https://github.com/dell/omivv/pull/42
