### ISSUE TITLE
Migrating a repository profile from legacy OMIVV to OMEVVP 

### ISSUE THREAD

**Issue by prasadrao-dell** [dell/omivv#6]
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Requirement Breakdown | Details
-- | --
Objective |  All the repository profiles in the OMIVV appliance should be migrated to OMEVV
Authentication/Authorization |  Authenticate using vCenter credentials (Basic Authorization) and "x_omivv-api-vcenter-identifier" (UUID of the vCenter) as a mandatory header.
List of the tasks in the workflow (in   order) |  <ul><li>Ensure that the vCenter user credentials and the corresponding vCenter UUID are accepted for both OMIVV and OMEVV</li><li>Comply with any input validation (see below)</li><li>Main script should collect the vCenter details like IP/Name, Repository details from the OMIVV IP/Name provided</li><li>Export the vCenter and Repository profiles to csv file</li><li>Extract the details required to create the repository profiles in OMEVV</li></ul>
Module type: Library and/or executable |  Both library and executable, when used as library, it should send the Repository details objects to the caller. When used as executable to export the details of vcenter and repository profile to csv file.
Input and format |  Script1 : Input – OMIVV IP/name , OMIVV creds, VC IP/name, VC creds      Script2 : Input – OMIVV IP/name , OMIVV creds, VC1 IP/name, VC1 creds, OMEVV IP/name, OMEVV creds, VC2 IP/name, VC2 creds  
Expected output and format   Export required |  Script1: Output – CSV file with all registered VC details and Repository profiles   Script2: Output – Repo profile details extracted from OMIVV , repo profile names with id created in OMEVV
Concurrency requirement. |  None
Execution model: synchronous or   asynchronous |  Synchronous
Applicable timeouts and retries |  Attempt up to 3 times only when the failure is on account of a network timeout to access vcenter details. On any other types of error for instance, providing invalid input parameters, no retry should be attempted.
Expected error handing |  Handle all the network and non network related errors and log them in a user friendly way.
Expected domain specific validation |  As mentioned above under Input and format

</body>

**Comment by pavithra-mahadev** [comment]
https://github.com/dell/omivv/pull/37

**Comment by pavithra-mahadev** [comment]
https://github.com/dell/omivv/pull/55
