### ISSUE TITLE
Creating a Baseline profile in OMEVVP

### ISSUE THREAD

**Issue by prasadrao-dell** [dell/omivv#7]
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Requirement Breakdown | Details
-- | --
Objective | Baseline Profile enables user to capture the baseline configuration for system configuration, firmware, or driver versions and maintain the desired state for clusters by identifying the drift against the baseline.
Authentication/Authorization | Authenticate using vCenter credentials (Basic Authorization) and "x_omivv-api-vcenter-identifier" (UUID of the vCenter) as a mandatory header.
List of the tasks in the workflow (in   order) |  <ul><li>Ensure that the vCenter user credentials and the corresponding vCenter UUID are accepted.</li><li>Comply with any input validation (see below)</li><li>Invoke request to create a baseline profile</li></li><li>Poll until the baseline profile is created</li><li>Return baseline profile object</li></ul>
Module type: Library and/or executable |  Both
Input and format |  <ul><li>Accept the following input properties<ul><li>groupIDs</li><li>baselineProfileName</li><li>firmware repo id</li><li>driver repo id</li><li>driftSchedule</li><ul><li>monday</li><li>tuesday</li><li>wednesday</li><li>thursday</li><li>friday</li><li>saturday</li><li>time</li><li>sunday</li></ul></ul></li><li>Accept the following input parameter - vCenter uuid</li></ul>
Expected output and format   Export required | Add log message at various execution steps if provided else output to console. Export is not required.
Concurrency requirement. | None
Execution model: synchronous or   asynchronous | Synchronous
Applicable timeouts and retries | Attempt creating the baseline profile upto 3 times only when the failure is on account of a network timeout. On any other types of error for instance, providing invalid input parameters, no retry should be attempted.
Expected error handing | Handle all the network and non network related errors and log them in a user friendly way.
Expected domain specific validation | As specified above

</body>

**Comment by pavithra-mahadev** [comment]
https://github.com/dell/omivv/pull/39
