### ISSUE TITLE
Collect and export the cluster profiles in OMIVV

### ISSUE THREAD

**Issue by prasadrao-dell** [dell/omivv#8]
<body lang=EN-US style='tab-interval:.5in;word-wrap:break-word'>

Requirement Breakdown | Details
-- | --
Objective |  All the cluster profiles in the OMIVV appliance should be exported to csv file
Authentication/Authorization |  Authenticate using basic token.
List of the tasks in the workflow (in   order) |  <ul><li>Ensure that the vCenter user credentials and the corresponding vCenter UUID are accepted for OMIVV</li><li>Comply with any input validation (see below)</li><li>Main script should collect the cluster profile details from the OMIVV IP/Name provided</li><li>Export the cluster profiles of the specified VC to csv file</li></ul>
Module type: Library and/or executable |  Existing executable should be enhanced. When used as library, should return the cluster profile objects.
Input and format |  Script1 : Input – OMIVV IP/name , OMIVV creds, VC IP/name, VC creds    
Expected output and format   Export required |  Script1: Output – CSV file with all cluster profiles of specified VC 
Concurrency requirement. |  None
Execution model: synchronous or   asynchronous |  Synchronous
Applicable timeouts and retries |  Attempt up to 3 times only when the failure is on account of a network timeout to access vcenter details. On any other types of error for instance, providing invalid input parameters, no retry should be attempted.
Expected error handing |  Handle all the network and non network related errors and log them in a user friendly way.
Expected domain specific validation |  As mentioned above under Input and format

</body>

**Comment by pavithra-mahadev** [comment]
https://github.com/dell/omivv/pull/51
